CREATE TABLE [dbo].[Classes]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(24) NOT NULL UNIQUE, 
    [TeacherId] INT NULL, 
    CONSTRAINT [FK_Classes_Users] FOREIGN KEY ([TeacherId]) REFERENCES [Users]([Id]) ON DELETE NO ACTION ON UPDATE NO ACTION
)
